import { useState } from 'react';
import { Eye, FileText, Copy, Code } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { useToast } from '@/hooks/use-toast';

const documentTemplates = [
  {
    type: 'ORDER_FORM',
    title: 'Bon de Commande',
    description: 'Order form template for vehicle purchases',
    placeholders: {
      '{{order_id}}': 'Unique order identifier',
      '{{client_info}}': 'Client name and contact details',
      '{{vehicle_list}}': 'List of ordered vehicles',
      '{{total_amount}}': 'Total order amount',
      '{{order_date}}': 'Date of order creation',
    },
  },
  {
    type: 'REGISTRATION_REQUEST',
    title: 'Demande d\'Immatriculation',
    description: 'Vehicle registration request document',
    placeholders: {
      '{{vehicle_info}}': 'Vehicle make, model, VIN',
      '{{owner_info}}': 'Owner details',
      '{{registration_date}}': 'Registration date',
    },
  },
  {
    type: 'TRANSFER_CERTIFICATE',
    title: 'Certificat de Cession',
    description: 'Vehicle transfer certificate',
    placeholders: {
      '{{seller_info}}': 'Seller details',
      '{{buyer_info}}': 'Buyer details',
      '{{vehicle_info}}': 'Vehicle details',
      '{{transfer_date}}': 'Transfer date',
    },
  },
  {
    type: 'INVOICE',
    title: 'Facture',
    description: 'Invoice document for completed orders',
    placeholders: {
      '{{invoice_number}}': 'Invoice reference number',
      '{{client_info}}': 'Client billing information',
      '{{line_items}}': 'Detailed line items',
      '{{subtotal}}': 'Subtotal before tax',
      '{{tax}}': 'Tax amount',
      '{{total}}': 'Total amount due',
    },
  },
];

const DocumentTemplates = () => {
  const [selectedTemplate, setSelectedTemplate] = useState(documentTemplates[0]);
  const [viewMode, setViewMode] = useState<'preview' | 'placeholders'>('preview');
  const { toast } = useToast();

  const copyPlaceholder = (placeholder: string) => {
    navigator.clipboard.writeText(placeholder);
    toast({
      title: 'Copied!',
      description: `${placeholder} copied to clipboard`,
    });
  };

  const sampleHtml = `
<!DOCTYPE html>
<html>
<head>
  <title>${selectedTemplate.title}</title>
  <style>
    body { font-family: Arial, sans-serif; padding: 40px; }
    .header { text-align: center; border-bottom: 2px solid #1E40AF; padding-bottom: 20px; }
    .title { color: #1E40AF; font-size: 24px; font-weight: bold; }
    .subtitle { color: #666; margin-top: 5px; }
    .content { margin-top: 30px; }
    .field { margin: 15px 0; }
    .label { font-weight: bold; color: #333; }
    .value { color: #666; padding: 10px; background: #f5f5f5; border-radius: 5px; margin-top: 5px; }
    .footer { margin-top: 40px; text-align: center; color: #999; font-size: 12px; }
  </style>
</head>
<body>
  <div class="header">
    <div class="title">DriveDeal - ${selectedTemplate.title}</div>
    <div class="subtitle">Document Template</div>
  </div>
  <div class="content">
    ${Object.entries(selectedTemplate.placeholders)
      .map(
        ([placeholder, desc]) => `
    <div class="field">
      <div class="label">${desc}</div>
      <div class="value">${placeholder}</div>
    </div>`
      )
      .join('')}
  </div>
  <div class="footer">
    Generated by DriveDeal Document System
  </div>
</body>
</html>`;

  return (
    <div className="min-h-screen py-12 bg-muted/30">
      <div className="container mx-auto px-4">
        {/* Header */}
        <div className="text-center space-y-4 mb-12">
          <span className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-primary/10 text-primary text-sm font-medium">
            Singleton Pattern
          </span>
          <h1 className="section-heading">Document Templates</h1>
          <p className="text-lg text-muted-foreground max-w-2xl mx-auto">
            View and manage blank document templates with placeholders
          </p>
        </div>

        <div className="max-w-6xl mx-auto grid lg:grid-cols-3 gap-8">
          {/* Template List */}
          <div className="space-y-4">
            <h3 className="font-display font-bold text-lg">Available Templates</h3>
            {documentTemplates.map((template) => (
              <button
                key={template.type}
                onClick={() => setSelectedTemplate(template)}
                className={`w-full p-4 rounded-xl border text-left transition-all ${
                  selectedTemplate.type === template.type
                    ? 'border-primary bg-primary/5 ring-2 ring-primary/20'
                    : 'border-border hover:border-primary/50'
                }`}
              >
                <div className="flex items-start gap-3">
                  <div
                    className={`p-2 rounded-lg ${
                      selectedTemplate.type === template.type
                        ? 'bg-primary text-primary-foreground'
                        : 'bg-muted text-muted-foreground'
                    }`}
                  >
                    <FileText className="w-5 h-5" />
                  </div>
                  <div>
                    <div className="font-semibold">{template.title}</div>
                    <div className="text-sm text-muted-foreground">{template.type}</div>
                  </div>
                </div>
              </button>
            ))}
          </div>

          {/* Template Preview */}
          <div className="lg:col-span-2">
            <Card>
              <CardHeader>
                <div className="flex items-center justify-between">
                  <div>
                    <CardTitle className="font-display">{selectedTemplate.title}</CardTitle>
                    <CardDescription>{selectedTemplate.description}</CardDescription>
                  </div>
                  <Tabs value={viewMode} onValueChange={(v) => setViewMode(v as 'preview' | 'placeholders')}>
                    <TabsList>
                      <TabsTrigger value="preview" className="gap-1">
                        <Eye className="w-4 h-4" />
                        Preview
                      </TabsTrigger>
                      <TabsTrigger value="placeholders" className="gap-1">
                        <Code className="w-4 h-4" />
                        Placeholders
                      </TabsTrigger>
                    </TabsList>
                  </Tabs>
                </div>
              </CardHeader>
              <CardContent>
                {viewMode === 'preview' ? (
                  <div className="rounded-lg border border-border overflow-hidden bg-white">
                    <iframe
                      srcDoc={sampleHtml}
                      className="w-full h-[500px]"
                      title="Template Preview"
                    />
                  </div>
                ) : (
                  <div className="space-y-4">
                    <p className="text-sm text-muted-foreground">
                      Click on any placeholder to copy it to your clipboard
                    </p>
                    <div className="grid gap-3">
                      {Object.entries(selectedTemplate.placeholders).map(([placeholder, description]) => (
                        <button
                          key={placeholder}
                          onClick={() => copyPlaceholder(placeholder)}
                          className="flex items-center justify-between p-4 rounded-lg border border-border hover:border-primary hover:bg-primary/5 transition-all group"
                        >
                          <div className="text-left">
                            <code className="text-primary font-mono text-sm">{placeholder}</code>
                            <div className="text-sm text-muted-foreground mt-1">{description}</div>
                          </div>
                          <Copy className="w-4 h-4 text-muted-foreground group-hover:text-primary" />
                        </button>
                      ))}
                    </div>
                  </div>
                )}
              </CardContent>
            </Card>

            {/* API Info */}
            <Card className="mt-6">
              <CardHeader>
                <CardTitle className="font-display text-lg">API Endpoint</CardTitle>
              </CardHeader>
              <CardContent>
                <div className="p-4 rounded-lg bg-muted font-mono text-sm">
                  <span className="text-emerald-600">GET</span>{' '}
                  <span className="text-muted-foreground">/api/documents/template/</span>
                  <span className="text-primary">{selectedTemplate.type}</span>
                </div>
                <p className="text-sm text-muted-foreground mt-3">
                  Returns the blank template with all available placeholders for customization.
                </p>
              </CardContent>
            </Card>
          </div>
        </div>
      </div>
    </div>
  );
};

export default DocumentTemplates;
